export const DIETARY_OPTIONS = [
    "Vegan",
    "Vegetarian",
    "Keto",
    "Flexitarian",
    "Pescatarian",
    "Paleo",
    "Raw",
    "Gluten Free",
    "Grain Free",
    "Bulking",
    "Low Sodium",
    "Low Calorie",
    "High Protein",
    "Sugar Free",
    "Lactose Intolerant",
    "Egg Free",
    "Nut Free",
    "Soy Free",
    "Shellfish Free",
    "Nightshade Free",
    "Low-FODMAP",
    "Kosher",
    "Halal",
    "Cutting",
    "Alcohol Free",
    "Organic",
    "Diabetic",
    "Chrones"
  ];