export const DIETARY_OPTIONS = [
    "Vegan",
    "Vegetarian",
    "Keto",
    "Flexitarian",
    "Pescatarian",
    "Paleo",
    "Raw",
    "Gluten Free",
    "Grain Free",
    "Bulking",
    "Low Sodium",
    "Low Calorie",
    "High Protein",
    "Sugar Free",
    "Lactose Intolerant",
    "Egg Free",
    "Nut Free",
    "Soy Free",
    "Shellfish Free",
    "Nightshade Free",
    "Low-FODMAP",
    "Kosher",
    "Halal",
    "Cutting",
    "Alcohol Free",
    "Organic",
    "Diabetic",
    "Chrones"
  ];

  export const EXPERIENCES = [
    "Breakfast Fast",
    "Breakfast Sit Down",
    "Brunch",
    "Lunch Fast",
    "Lunch Sit Down",
    "Lunch Business",
    "Dinner Fast",
    "Dinner Sit Down",
    "Dinner Business",
    "Late Night",
    "Desserts",
    "Drinks",
    "Coffee/Tea",
    "Hidden Gem",
    "Casual",
    "Fine Dining",
    "Family-Friendly",
    "Outdoor/Patio", 
    "Ethnic/Cultural",
    "Romantic",
    "Budget-Friendly"
  ];

  export const CUISINES = [
    "Italian",
    "Mexican", 
    "Chinese",
    "Japanese",
    "Thai",
    "Indian", 
    "Greek",
    "Korean",
    "Vietnamese",
    "American"
  ];
